name: restaurante_popular
description: Aplicativo do Restaurante Popular Maranhão
publish_to: 'none' 

version: 1.0.1+3

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  flutter_html: ^3.0.0
  google_maps_flutter: ^2.6.0
  geolocator: ^11.0.0
  geocoding: ^2.2.0
  permission_handler: ^11.3.0
  http: ^1.2.1
  firebase_core: ^2.30.0
  firebase_messaging: ^14.7.10
  cupertino_icons: ^1.0.2
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  video_player: ^2.8.2
  smooth_page_indicator: ^1.1.0
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  change_app_package_name: ^1.5.0
  connectivity_plus: ^6.1.0
  internet_connection_checker: ^1.0.0
  flutter_launcher_icons: ^0.14.4
  lottie: ^3.1.0
  url_launcher: ^6.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.10
  hive_generator: ^2.0.1

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/logo.svg
    - assets/images/logo_governo.png
    - assets/images/sobre1.png
    - assets/images/sobre2.png
    - assets/images/sobre3.png
    - assets/images/logo.svg
    - assets/images/almoco.png
    - assets/images/cafe.png
    - assets/images/jantar.png
    - assets/images/splash.mp4