platform :ios, '14.0'

use_frameworks!
use_modular_headers!

# ⚠️ Defina as funções primeiro
def flutter_install_all_ios_pods(app_dir)
  plugin_deps_path = File.join(app_dir, '.flutter-plugins-dependencies')

  if File.exist?(plugin_deps_path)
    plugin_pods = File.read(plugin_deps_path)
    plugins = JSON.parse(plugin_pods)["plugins"]["ios"]
    plugins.each do |plugin|
      pod plugin["name"], :path => plugin["path"]
    end
  else
    # fallback mínimo
    pod 'Flutter', :path => '../Flutter'
  end
end

# ✅ Só depois chame a função
target 'Runner' do
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
